#ifndef __spss2psrfits_cmd__
#define __spss2psrfits_cmd__
/*****
  command line parser interface -- generated by clig 
  (http://wsd.iitb.fhg.de/~geg/clighome/)

  The command line parser `clig':
  (C) 1995-2004 Harald Kirsch (clig@geggus.net)
*****/

typedef struct s_Cmdline {
  /***** -o: Name of the output psrfits file */
  char outfileP;
  char* outfile;
  int outfileC;
  /***** -g: Approx length in GB of output data files */
  char outlenGBP;
  int outlenGB;
  int outlenGBC;
  /***** -i: iBOBs to ignore (no spaces) */
  char ignoredP;
  char* ignored;
  int ignoredC;
  /***** uninterpreted command line parameters */
  int argc;
  /*@null*/char **argv;
  /***** the whole command line concatenated */
  char *full_cmd_line;
} Cmdline;


extern char *Program;
extern void usage(void);
extern /*@shared*/Cmdline *parseCmdline(int argc, char **argv);

extern void showOptionValues(void);

#endif

